const ActionTypes = {
    SIGNUP_SUCCESS : "SIGNUP_SUCCESS",
    SIGNUP_FAILURE : "SIGNUP_FAILURE",
    SIGNIN_SUCCESS : "SIGNIN_SUCCESS",
    SIGNIN_FAILURE : "SIGNIN_FAILURE",
    WRITTEN_ERROR : "WRITTEN_ERROR",
    WRITTEN_SUCCESS : "WRITTEN_SUCCESS",
    TODO_ADD_SUCCESS : "TODO_ADD_SUCCESS",
    GET_TODO_SUCCESS : "GET_TODO_SUCCESS",
    ADD_TODO : "ADD_TODO",
    ERROR : "ERROR",
    SUCCESS : "SUCCESS" ,
}

export default ActionTypes;
